export type HomeLang = 'ko' | 'en' | 'ja' | 'zh'

// ── Use Case Personas (언어 무관 공통 아이콘·컬러) ─────────────────────────
export const USE_CASE_META = [
  { icon: '🛒', color: '#FF9900', accent: 'from-orange-500/20 to-amber-500/10',  border: 'border-orange-500/20' },
  { icon: '📋', color: '#6366F1', accent: 'from-indigo-500/20 to-violet-500/10', border: 'border-indigo-500/20' },
  { icon: '🎓', color: '#10B981', accent: 'from-emerald-500/20 to-teal-500/10',  border: 'border-emerald-500/20' },
  { icon: '🏢', color: '#3B82F6', accent: 'from-blue-500/20 to-cyan-500/10',     border: 'border-blue-500/20' },
  { icon: '✍️', color: '#EC4899', accent: 'from-pink-500/20 to-rose-500/10',     border: 'border-pink-500/20' },
  { icon: '🌏', color: '#8B5CF6', accent: 'from-violet-500/20 to-purple-500/10', border: 'border-violet-500/20' },
]

// ── Comparison Table ────────────────────────────────────────────────────────
export const COMPARISON_COLS = ['outsource', 'chatgpt', 'pageai'] as const
export type CompareCol = typeof COMPARISON_COLS[number]

export const PLATFORMS = [
  { name: 'Amazon JP', color: '#FF9900' },
  { name: 'Tmall', color: '#E43226' },
  { name: '楽天 Rakuten', color: '#BF0000' },
  { name: 'Shopify', color: '#96BF48' },
  { name: 'Qoo10', color: '#E1261C' },
  { name: 'Lazada', color: '#F57226' },
  { name: 'Smartstore', color: '#03C75A' },
]

export const LANG_TABS = [
  { flag: '🇰🇷', code: 'KR', name: { ko: '한국어', en: 'Korean', ja: '韓国語', zh: '韩语' }, platform: 'Smartstore · Coupang', style: { ko: '감성적 톤, SEO 최적화', en: 'Emotional tone, SEO', ja: '感情的なトーン', zh: '情感化风格' }, color: 'from-blue-500 to-blue-600', glow: 'shadow-blue-500/30' },
  { flag: '🇺🇸', code: 'EN', name: { ko: '영어', en: 'English', ja: '英語', zh: '英语' }, platform: 'Amazon JP · Shopify', style: { ko: 'Benefit-first, 데이터 기반', en: 'Benefit-first, data-driven', ja: 'ベネフィット重視', zh: '利益优先风格' }, color: 'from-violet-500 to-purple-600', glow: 'shadow-violet-500/30' },
  { flag: '🇯🇵', code: 'JP', name: { ko: '일본어', en: 'Japanese', ja: '日本語', zh: '日语' }, platform: '楽天 · Yahoo! Japan', style: { ko: '경어체, 계절감 강조', en: 'Keigo style, seasonal', ja: '敬語スタイル・季節感', zh: '敬语风格·季节感' }, color: 'from-rose-500 to-pink-600', glow: 'shadow-rose-500/30' },
  { flag: '🇨🇳', code: 'CN', name: { ko: '중국어', en: 'Chinese', ja: '中国語', zh: '中文' }, platform: 'Tmall · JD.com', style: { ko: '天猫爆款 · 사회적 증거', en: '天猫爆款 · Social proof', ja: '天猫爆款スタイル', zh: '天猫爆款·社交证明' }, color: 'from-amber-500 to-orange-500', glow: 'shadow-amber-500/30' },
]

export const HOME_COPY = {
  ko: {
    nav: { how: '작동 방식', features: '주요 기능', reviews: '후기', pricing: '가격', blog: '블로그', signin: '로그인', startFree: '무료 시작' },
    hero: {
      badge: '🔥 1,200+ 글로벌 셀러 & 전문가 사용 중',
      h1a: '양식·URL만 올리면', h1b: 'AI가 5분 안에 완성', h1c: '4개 언어, 글로벌 플랫폼 최적화까지.',
      sub1: '상세페이지 · 사업계획서 · 제안서 · 보고서 · 과제 — PDF·DOCX 어떤 양식이든.',
      sub1b: '',
      sub2: 'Amazon JP · Tmall · Rakuten · Shopify · Smartstore — 플랫폼별 완벽 최적화.',
      cta1: '무료로 시작하기', cta2: '데모 보기 ▶',
      stats: [['5분', '전문가 수준 완성'], ['4개 언어', '동시 생성'], ['95%', '외주 비용 절감'], ['무료', '시작 가능']],
    },
    crossborder: {
      title: '크로스보더 모드', badge: 'NEW',
      desc1: '4개 언어 + 글로벌 플랫폼 최적화',
      desc2: ' — 1번 입력, 4개국 동시 런칭, 외주 불필요.',
      cta: '무료로 시작 →',
    },
    template: {
      badge: '📋 AI 양식 자동완성',
      h2a: '양식만 올리면', h2b: 'AI가 전문가처럼 채워드립니다.',
      sub: '과제·시험지·사업계획서·제안서·보고서·신청서 — PDF·DOCX·XLSX 어떤 형식이든',
      types: ['📝 과제·시험지', '💼 사업계획서', '📊 성과 보고서', '📝 제안서·RFP', '🏛 공공기관 신청서', '🔬 연구·논문', '🎓 학술 보고서', '📋 IR 피칭 덱'],
      flow: [
        { step: '01', title: '양식 업로드', desc: 'PDF·DOCX·XLSX·PPTX 첨부 또는 텍스트 붙여넣기', icon: '📤' },
        { step: '02', title: 'AI 자동 분석', desc: '양식 구조를 파악하고 모든 항목을 자동으로 채움', icon: '⚡' },
        { step: '03', title: '전문가 수준 완성', desc: '4개 언어 동시 생성 가능. PDF·DOCX 다운로드', icon: '✅' },
      ],
      cta: '양식 자동완성 무료로 시작 →',
      proof: '베타 사용자 기준 평균 작성 시간 92% 단축',
      demo: {
        dragDrop: '드래그하거나 클릭해서 업로드',
        fileBtn: '파일 선택',
        parsed: '양식 파싱 완료 — 사업계획서.docx',
        fields: [['회사명', 'PageAI Inc.'], ['사업 목적', 'AI 기반 문서 자동화 SaaS'], ['목표 시장', '한국·일본·중국 크로스보더'], ['예상 매출', '1억원 (1년차)']],
        multiLang: '4개 언어 동시 생성',
        startBtn: '⚡ AI 자동 완성 시작',
      },
    },
    platformBar: '글로벌 주요 플랫폼 자동 최적화',
    how: {
      label: '작동 방식',
      h2a: '아이디어에서 4개국어 콘텐츠까지',
      h2b: '2분 이내.',
      steps: [
        { n: '01', icon: '🔗', title: 'URL 또는 제품 설명 입력', desc: '스마트스토어·Amazon·Tmall·Shopify URL을 붙여넣거나 간단히 제품을 설명하세요. AI가 모든 항목을 자동으로 채웁니다.', badge: '~30초' },
        { n: '02', icon: '⚡', title: 'AI가 4개 언어를 동시 생성', desc: '클릭 1번 → 한국어·영어·일본어·중국어 동시 생성. 번역이 아닌 진짜 문화 현지화.', badge: '~60초' },
        { n: '03', icon: '📦', title: '내보내기 & 바로 발행', desc: 'ZIP 다운로드, 플랫폼 복사, PDF 내보내기. Amazon A+, Tmall 详情页, 楽天商品ページ — 형식 완벽 맞춤.', badge: '클릭 1번' },
      ],
    },
    features: {
      label: '주요 기능',
      h2a: '글로벌 셀러에게',
      h2b: '진짜 필요한 모든 것.',
      card1: { badge: '🌏 핵심 기능', title: '4개 언어 동시 생성', desc: '1번 입력, 4가지 문화 맞춤 결과물. 일본어는 경어체, 중국어는 天猫爆款, 영어는 Amazon A+ 형식.' },
      card2: { title: 'URL 자동 입력', desc: '제품 URL을 붙여넣으면 AI가 10초 만에 분석해 모든 항목을 자동으로 채웁니다.' },
      card3: { title: '전환율 예측기', desc: '생성 후 시장별 예상 전환율(CVR)을 자동으로 제공합니다.' },
      card4: { badge: '🛒 플랫폼 인텔리전스', title: '모든 플랫폼 자동 최적화', desc: '플랫폼 선택 → 콘텐츠 자동 포맷. Amazon A+(5개 불릿), Tmall 상세페이지, 楽天상품 페이지. 수동 작업 제로.' },
    },
    demo: {
      label: '라이브 데모',
      h2a: '자동 발행 흐름을',
      h2b: '실시간으로 확인하세요.',
      sub: '입력 → AI 4개국어 동시 생성 → Amazon · Tmall · 楽天 · Shopify 최적화',
    },
    stats: [
      { v: '4', unit: '개 언어', sub: '1회 생성', color: 'from-blue-600 to-violet-600' },
      { v: '6', unit: '개 플랫폼', sub: '자동 최적화', color: 'from-emerald-500 to-teal-500' },
      { v: '2×', unit: '전환율', sub: '단순 번역 대비', color: 'from-orange-500 to-amber-400' },
      { v: '95%', unit: '비용 절감', sub: '외주 대비', color: 'from-rose-500 to-pink-500' },
    ],
    data: {
      label: '실제 셀러 성과 — 베타 테스터 데이터',
      items: [
        { before: '2주', after: '5분', label: '콘텐츠 제작 시간', delta: '↓97%', color: 'text-blue-600', bg: 'bg-blue-50 border-blue-200' },
        { before: '$2,400', after: '$29', label: '4개국어 콘텐츠 비용/월', delta: '↓99%', color: 'text-violet-600', bg: 'bg-violet-50 border-violet-200' },
        { before: '1.2%', after: '2.8%', label: 'Amazon JP 전환율', delta: '+133%', color: 'text-emerald-600', bg: 'bg-emerald-50 border-emerald-200' },
        { before: '1개국', after: '4개국', label: '동시 런칭 시장', delta: '4×', color: 'text-orange-500', bg: 'bg-orange-50 border-orange-200' },
      ],
    },
    reviews: {
      label: '실사용자 후기',
      h2a: '전환한 셀러들은',
      h2b: '돌아가지 않았습니다.',
      items: [
        { name: '이지윤', role: '뷰티 크로스보더 셀러 (KR→JP)', badge: '번역비 90% 절감', text: '楽天 경어체가 바로 나와요. 오역 없이. 번역가 비용 월 40만원 아꼈습니다.' },
        { name: '고우빈', role: 'Amazon JP 셀러', badge: 'Amazon 런칭 5배 빠름', text: 'Amazon A+ Content 불릿 포인트가 자동으로 딱 맞게 나와요. 카피라이터 없이 런칭 속도가 완전 달라졌습니다.' },
        { name: '신재연', role: 'Tmall 글로벌 브랜드 담당자', badge: 'Tmall CTR +22%', text: '天猫爆款 스타일로 한 번에 나와요. 단순 번역이 아닌 진짜 현지화. CTR이 일주일 만에 올랐습니다.' },
        { name: '조수양', role: 'D2C 헬스케어 브랜드 대표', badge: '4개국 동시 출시', text: 'KR·EN·JP·CN이 동시에 나오는 게 정말 게임 체인저예요. 각 언어를 따로 외주 줬는데, 이제 혼자서 4개국 동시 출시합니다.' },
        { name: '박민준', role: 'Qoo10 뷰티 셀러', badge: '플랫폼 최적화 자동', text: '크로스보더 모드 → Qoo10 선택 → 딱 맞는 형식. 복사해서 바로 붙이면 끝. 완전 편해졌어요.' },
        { name: '김서현', role: 'Shopify 글로벌 스토어', badge: '전환율 2배 향상', text: 'EN·JP·CN을 동시에 문화 뉘앙스까지 맞춰서 써주는 AI가 없었어요. PageAI가 유일하게 진짜 현지화를 합니다.' },
      ],
    },
    faq: {
      label: 'FAQ',
      h2a: '자주 묻는 질문에',
      h2b: '답해드립니다.',
      items: [
        { q: '4개 언어를 진짜 동시에 생성할 수 있나요?', a: '네. "전체 언어" 선택 시 한국어·영어·일본어·중국어를 한 번에 생성합니다. 번역이 아닌 각 언어에 맞는 문화 현지화 — 일본어는 경어체, 중국어는 天猫 스타일, 영어는 Amazon A+ 형식입니다.' },
        { q: 'Amazon JP, Tmall, 楽天에 바로 사용할 수 있나요?', a: '네. 크로스보더 모드에서 플랫폼을 선택하면 Amazon A+(5개 불릿), Tmall 상세페이지 구조, 楽天 상품 설명 형식으로 자동 포맷됩니다. 수동 수정 불필요.' },
        { q: '번역이 아니라 진짜 현지화인가요?', a: '진짜 현지화입니다. 일본은 경어·품질 신뢰·계절감, 중국은 KOL 언급·사회적 증거·프로모션, 영어는 혜택 우선·수치 신뢰 구조. 번역과는 완전히 다릅니다.' },
        { q: 'URL만 넣으면 자동으로 입력되나요?', a: '네. 스마트스토어·쿠팡·Amazon·Shopify 어떤 URL이든 붙여넣으면 AI가 10초 만에 분석해서 제품명·카테고리·설명을 자동으로 채웁니다.' },
        { q: '1세트 만드는 데 얼마나 걸리나요?', a: '입력 30초 + 생성 60초 = 총 2분 이내. 다국어 외주를 맡겼다면 2주 이상 기다려야 했을 작업입니다.' },
        { q: '외주 비용과 비교하면 얼마나 절약되나요?', a: '다국어 외주 제작비: 월 100~320만원. PageAI Pro(월 3만9천원) = 무제한 생성. 95% 이상 비용 절감입니다.' },
      ],
    },
    useCases: {
      label: '누가 사용하나요',
      h2a: '셀러부터 대학원생까지',
      h2b: '모두가 5분을 되찾습니다.',
      items: [
        { title: '크로스보더 셀러', role: 'Amazon JP · Tmall · Rakuten', pain: '플랫폼별 상세페이지를 각각 외주 맡기느라 월 수백만원', gain: '1번 입력 → 4개국어 플랫폼 최적화 동시 완성. 외주비 95% 절감.' },
        { title: '사업계획서·제안서 작성자', role: '스타트업 창업자 · 컨설턴트', pain: '사업계획서 빈칸 채우는 데 며칠씩 소요', gain: '양식 업로드 → AI가 모든 항목을 논리적으로 자동 완성.' },
        { title: '대학생·대학원생', role: '과제·시험·논문 작성', pain: '과제 양식 이해하고 채우는 데 반나절', gain: 'PDF 과제 업로드 → AI가 학술적 스타일로 전 항목 완성.' },
        { title: '기업 마케터·담당자', role: 'B2B 제안서 · IR 덱', pain: 'IR 피칭 덱, RFP 제안서를 처음부터 작성하는 부담', gain: '기존 양식 첨부 → AI가 설득력 있는 내용으로 채워줌.' },
        { title: '콘텐츠 크리에이터', role: '네이버 블로그 · SNS 마케팅', pain: 'SEO 최적화 리뷰 글 작성에 시간 과다 투입', gain: 'URL만 입력 → 플랫폼 스타일에 맞는 자연스러운 리뷰 자동 생성.' },
        { title: '글로벌 브랜드 담당자', role: '4개국 동시 런칭 캠페인', pain: '언어별 에이전시 관리 + 번역 QA로 수주일 소요', gain: '1번 작성 → 4개 언어 문화 현지화 동시 완성. 수주를 하루로.' },
      ],
    },
    comparison: {
      label: '왜 PageAI인가',
      h2a: '외주·ChatGPT와',
      h2b: '직접 비교해봤습니다.',
      rows: [
        { feature: '4개 언어 동시 생성', outsource: false, chatgpt: '△ 직접 반복', pageai: true },
        { feature: '플랫폼별 자동 포맷 (Amazon A+, Tmall 등)', outsource: true, chatgpt: false, pageai: true },
        { feature: '양식·PDF 자동 분석 & 완성', outsource: '△ 수동 전달', chatgpt: false, pageai: true },
        { feature: 'URL → 자동 제품정보 추출', outsource: false, chatgpt: false, pageai: true },
        { feature: '문화적 현지화 (번역 아님)', outsource: '△ 비용 별도', chatgpt: '△ 프롬프트 수동', pageai: true },
        { feature: '비용', outsource: '월 100~320만원', chatgpt: '$20/월 (수동)', pageai: '무료로 시작' },
        { feature: '완성까지 시간', outsource: '3~14일', chatgpt: '1~3시간', pageai: '5분 이내' },
      ],
      cols: { outsource: '외주 에이전시', chatgpt: 'ChatGPT·Claude', pageai: 'PageAI ✓' },
    },
    finalCta: {
      label: '지금 바로 시작하세요',
      h2a: '첫 번째 문서는',
      h2b: '무료입니다.',
      sub1: '신용카드 불필요 · 30초면 시작 · 즉시 사용 가능',
      sub2: '🇰🇷 한국어 · 🇺🇸 영어 · 🇯🇵 일본어 · 🇨🇳 중국어',
      cta: '무료로 시작하기 →',
    },
    footer: {
      desc: '양식·URL만 올리면 AI가 5분 만에 전문가 수준 문서를 완성합니다. 4개국어로.',
      links: [['/', '홈'],['#features', '주요 기능'],['#reviews', '후기'],['#pricing', '가격'],['/blog', '블로그'],['/login', '로그인'],['/samples', '샘플'],['/privacy', '개인정보']],
      copy: '© 2026 PageAI · pagebeer.beer. 모든 권리 보유.',
      privacy: '개인정보처리방침', terms: '이용약관',
      floatingCta: '무료로 시작하기 →',
    },
  },

  en: {
    nav: { how: 'How it works', features: 'Features', reviews: 'Reviews', pricing: 'Pricing', blog: 'Blog', signin: 'Sign in', startFree: 'Start Free' },
    hero: {
      badge: '🔥 #1 AI Product Description Generator for Cross-Border eCommerce · 1,200+ Global Sellers',
      h1a: 'Create Perfect Product Pages', h1b: 'in 4 Languages in 5 Minutes —', h1c: 'AI-Optimized for Every Global Platform.',
      sub1: 'Amazon JP · Tmall · Rakuten · Shopify · Smartstore product pages,',
      sub1b: 'plus business plans, proposals & reports — AI auto-fills any form at expert level.',
      sub2: 'The only AI tool that generates culturally-localized content for KR · EN · JP · CN simultaneously.',
      cta1: 'Start Free Now', cta2: 'See How It Works ▶',
      stats: [['5 min', 'expert-level content'], ['4 languages', 'simultaneously'], ['95%', 'cost vs outsourcing'], ['Free', 'to start']],
    },
    crossborder: {
      title: 'Cross-Border AI Mode', badge: 'NEW',
      desc1: '4 Languages + Global Platform Optimization in One Click',
      desc2: ' — input once, launch in four countries, zero outsourcing needed.',
      cta: 'Try Cross-Border Mode Free →',
    },
    template: {
      badge: '📋 AI Form & Document Auto-Fill',
      h2a: 'Upload Any Form or Template.', h2b: 'AI Fills It Like a Domain Expert.',
      sub: 'Business Plans · Proposals · Reports · Assignments · Inspection Reports · Excel Sheets — PDF·DOCX·XLSX·HWP all supported',
      types: ['📝 Assignments & Exams', '💼 Business Plans', '📊 Inspection Reports', '📝 RFP / Proposals', '🏛 Grant Applications', '🔬 Research Papers', '🎓 Academic Reports', '📋 IR Pitch Decks'],
      flow: [
        { step: '01', title: 'Upload Your Form', desc: 'Attach PDF, DOCX, XLSX, PPTX, or paste text — any document format works', icon: '📤' },
        { step: '02', title: 'AI Analyzes & Auto-Fills', desc: 'AI detects form structure, interprets data, fills every field professionally', icon: '⚡' },
        { step: '03', title: 'Professional Document Ready', desc: 'Generate in 4 languages simultaneously. Download as PDF, DOCX, or TXT', icon: '✅' },
      ],
      cta: 'Try AI Document Auto-Fill Free →',
      proof: 'Beta users report 92% reduction in document writing time',
      demo: {
        dragDrop: 'Drag & drop or click to upload',
        fileBtn: 'Choose File',
        parsed: 'Form parsed — BusinessPlan.docx',
        fields: [['Company', 'PageAI Inc.'], ['Business Goal', 'AI Document Automation SaaS'], ['Target Market', 'Korea · Japan · China Cross-border'], ['Est. Revenue', '$1M (Year 1)']],
        multiLang: '4 languages simultaneously',
        startBtn: '⚡ Start AI Auto-Fill',
      },
    },
    platformBar: 'Auto-optimized for every major global eCommerce platform',
    how: {
      label: 'How it works',
      h2a: 'From product URL to 4-language',
      h2b: 'platform-ready content in 2 minutes.',
      steps: [
        { n: '01', icon: '🔗', title: 'Paste product URL or describe it', desc: 'Drop any product URL (Amazon, Tmall, Shopify, Smartstore…) or type a brief description. The AI product description generator auto-fills all fields in seconds.', badge: '~30 sec' },
        { n: '02', icon: '⚡', title: 'AI generates 4 languages at once', desc: 'One click → Korean · English · Japanese · Chinese simultaneously. Each version is culturally localized — not just translated. Japanese gets keigo, Chinese gets 天猫爆款 style.', badge: '~60 sec' },
        { n: '03', icon: '📦', title: 'Export & publish anywhere', desc: 'Download ZIP package, copy to Amazon Seller Central, or export PDF. Amazon A+ Content, Tmall 详情页, 楽天商品ページ — perfectly formatted for each platform.', badge: '1 click' },
      ],
    },
    features: {
      label: 'Core Features',
      h2a: 'Everything cross-border sellers',
      h2b: 'need to dominate global markets.',
      card1: { badge: '🌏 Flagship: 4-Language AI', title: 'AI Product Description Generator — 4 Languages at Once', desc: 'The best AI tool for cross-border ecommerce. One input generates Korean, English, Japanese, and Chinese content — each culturally adapted. Amazon A+ bullets for EN, 天猫爆款 social proof for CN, 楽天 keigo style for JP.' },
      card2: { title: 'URL → Auto Product Description', desc: 'Paste any product URL from Amazon, Shopify, Tmall, or Smartstore. AI scrapes, analyzes, and generates a complete multilingual product description in under 10 seconds.' },
      card3: { title: 'Conversion Rate Predictor', desc: 'Every generated listing includes estimated CVR uplift by market — backed by platform-specific data for Amazon JP, Tmall, Rakuten, Shopify, and more.' },
      card4: { badge: '🛒 Platform Intelligence Engine', title: 'Platform-Specific Content Optimization', desc: 'Select your target platform and AI auto-formats: Amazon A+ Content (5 benefit bullets), Tmall 详情页 long-scroll structure, 楽天 product description style, Shopify SEO-optimized copy. Zero manual reformatting.' },
    },
    demo: {
      label: 'Live Demo',
      h2a: 'Watch AI generate 4-language',
      h2b: 'product pages in real time.',
      sub: 'Input → AI generates KR·EN·JP·CN → auto-formats for Amazon · Tmall · Rakuten · Shopify',
    },
    stats: [
      { v: '4', unit: 'Languages', sub: 'generated per click', color: 'from-blue-600 to-violet-600' },
      { v: '13+', unit: 'Platforms', sub: 'auto-optimized', color: 'from-emerald-500 to-teal-500' },
      { v: '2×', unit: 'Higher CVR', sub: 'vs plain translation', color: 'from-orange-500 to-amber-400' },
      { v: '95%', unit: 'Cost cut', sub: 'vs outsourcing agencies', color: 'from-rose-500 to-pink-500' },
    ],
    data: {
      label: 'Real results from cross-border sellers — beta tester data',
      items: [
        { before: '2 weeks', after: '5 min', label: 'Product page creation time', delta: '↓97%', color: 'text-blue-600', bg: 'bg-blue-50 border-blue-200' },
        { before: '$2,400', after: '$29', label: '4-language content cost / month', delta: '↓99%', color: 'text-violet-600', bg: 'bg-violet-50 border-violet-200' },
        { before: '1.2%', after: '2.8%', label: 'Amazon JP conversion rate', delta: '+133%', color: 'text-emerald-600', bg: 'bg-emerald-50 border-emerald-200' },
        { before: '1 market', after: '4 markets', label: 'Simultaneous launch', delta: '4×', color: 'text-orange-500', bg: 'bg-orange-50 border-orange-200' },
      ],
    },
    reviews: {
      label: 'Real reviews from global sellers',
      h2a: 'Cross-border sellers who switched',
      h2b: 'to PageAI never went back.',
      items: [
        { name: 'Jiyoon Lee', role: 'Beauty Cross-border Seller · KR→JP', badge: '90% translation cost saved', text: 'Japanese Rakuten-style keigo output in seconds. No more nuance errors or mistranslations. Saved $300/month on translators while launching faster.' },
        { name: 'Woobin Ko', role: 'Amazon JP Seller · Electronics', badge: '5× faster Amazon listing creation', text: 'Amazon A+ Content with perfectly formatted 5 benefit bullets, auto-generated. No more copywriters. My cross-border launch speed is completely transformed.' },
        { name: 'Jaeyeon Shin', role: 'Tmall Global Brand Manager', badge: 'Tmall CTR +22% in one week', text: '天猫爆款 style content generated out of the box. Chinese localization is genuinely accurate with proper social proof — CTR jumped 22% within the first week.' },
        { name: 'Suyang Jo', role: 'D2C Healthcare Brand CEO', badge: '4-country simultaneous launch', text: 'KR · EN · JP · CN generated at once is a complete game changer for cross-border ecommerce. Used to outsource each language separately. Now I launch 4 countries alone, in one afternoon.' },
        { name: 'Minjun Park', role: 'Qoo10 & Shopify Seller', badge: 'Platform auto-optimized', text: 'Cross-border mode → select platforms → perfect format for each. Copy-paste and done. The AI product description generator for cross-border sellers that actually works.' },
        { name: 'Seohyun Kim', role: 'Shopify Global Store Owner', badge: '2× conversion rate lift', text: 'No other AI product description generator handles EN/JP/CN cultural nuance simultaneously. PageAI is genuinely in a class of its own for cross-border ecommerce.' },
      ],
    },
    faq: {
      label: 'FAQ — AI Product Description Generator',
      h2a: 'Questions about AI-powered',
      h2b: 'cross-border content generation?',
      items: [
        { q: 'What makes PageAI the best AI product description generator for cross-border ecommerce?', a: 'PageAI is the only AI tool that generates culturally-localized product descriptions in 4 languages (KR/EN/JP/CN) simultaneously — not just translation. Each language is optimized for its platform: Amazon A+ for English, 天猫爆款 for Chinese, 楽天 keigo style for Japanese. Plus it auto-fills any form or document template.' },
        { q: 'Can I generate Amazon JP, Tmall, and Rakuten listings simultaneously?', a: 'Yes. In Cross-Border Mode, select your platforms and AI generates platform-specific content: Amazon A+ (5 benefit bullets), Tmall 详情页 long-scroll structure, 楽天商品ページ style — all at once, all culturally adapted. Zero manual reformatting needed.' },
        { q: 'Is this real cultural localization or just machine translation?', a: 'Real cultural localization — completely different from machine translation. Japan: seasonal nuance, keigo formality, quality trust signals. China: KOL mentions, social proof numbers, promotion-first structure. English: benefit-first bullets, data credibility. Each market gets its own persuasion logic.' },
        { q: 'How does the AI product URL auto-fill work?', a: 'Paste any product URL from Amazon, Shopify, Smartstore, Coupang, or Tmall. AI scrapes and analyzes the page, then auto-fills the product name, category, key features, and description in ~10 seconds. You can verify and edit before generating.' },
        { q: 'Can PageAI auto-fill business plans, inspection reports, and Excel templates?', a: 'Yes. The AI document auto-fill feature supports PDF, DOCX, XLSX, PPTX, and HWP. Upload any form — business plans, inspection reports, proposals, assignments — and AI interprets the data, then outputs a complete professional document (not raw data).' },
        { q: 'How much cheaper is PageAI vs multilingual copywriting agencies?', a: 'Multilingual agency outsourcing: $800–$2,400/month. PageAI Pro ($29/mo) = unlimited multilingual product descriptions, documents, and listings. That\'s a 95%+ cost reduction with 200× faster turnaround.' },
      ],
    },
    useCases: {
      label: 'Who uses PageAI',
      h2a: 'From Amazon JP sellers',
      h2b: 'to startup founders — everyone saves hours.',
      items: [
        { title: 'Cross-Border eCommerce Sellers', role: 'Amazon JP · Tmall · Rakuten · Shopify', pain: 'Paying $800–$2,400/mo to agencies for per-platform product listings in each language', gain: 'One input → 4-language platform-optimized listings simultaneously. 95% cost cut, 200× faster.' },
        { title: 'Business Plan & Proposal Writers', role: 'Startup Founders · Consultants · Grant Writers', pain: 'Days filling out business plan templates, RFPs, or grant application forms from scratch', gain: 'Upload any template → AI fills every field with logical, data-driven, professional content in minutes.' },
        { title: 'Students & Researchers', role: 'Assignments · Academic Reports · Theses', pain: 'Half a day understanding complex assignment forms and writing every section from scratch', gain: 'Upload PDF assignment → AI completes every section in proper academic style, in any language.' },
        { title: 'Corporate Marketers & BD Teams', role: 'RFP Responses · IR Pitch Decks · Reports', pain: 'Building IR decks and RFP responses manually, repeating the same structure every time', gain: 'Attach existing template → AI generates persuasive, structured content instantly. Export as DOCX.' },
        { title: 'Content Creators & Bloggers', role: 'Naver Blog · Amazon Reviews · SNS', pain: 'Writing SEO-optimized, platform-native review content for each market manually', gain: 'Paste product URL → AI generates naturally-written, platform-specific review copy in seconds.' },
        { title: 'Global Brand Managers', role: '4-Country Campaign Launch', pain: 'Coordinating translation agencies across 4 languages — weeks of QA and revision rounds', gain: 'Draft once → 4-language cultural localization complete in the same day. Eliminate agency dependency.' },
      ],
    },
    comparison: {
      label: 'Why PageAI vs ChatGPT vs Outsourcing',
      h2a: 'The best AI product description',
      h2b: 'generator for cross-border sellers.',
      rows: [
        { feature: '4-language simultaneous generation (KR/EN/JP/CN)', outsource: false, chatgpt: '△ repeat manually per language', pageai: true },
        { feature: 'Platform-specific auto-format (Amazon A+, Tmall, Rakuten…)', outsource: true, chatgpt: false, pageai: true },
        { feature: 'Form & Excel auto-analysis → professional document', outsource: '△ requires full manual briefing', chatgpt: false, pageai: true },
        { feature: 'URL → instant product description extraction', outsource: false, chatgpt: false, pageai: true },
        { feature: 'True cultural localization (not just translation)', outsource: '△ premium extra cost', chatgpt: '△ needs expert manual prompting', pageai: true },
        { feature: 'Price', outsource: '$800–$2,400/mo', chatgpt: '$20/mo (fully manual)', pageai: 'Free to start' },
        { feature: 'Turnaround time', outsource: '3–14 business days', chatgpt: '1–3 hours of manual prompting', pageai: 'Under 5 minutes' },
      ],
      cols: { outsource: 'Outsourcing Agency', chatgpt: 'ChatGPT / Claude', pageai: 'PageAI ✓' },
    },
    finalCta: {
      label: 'Start generating cross-border content for free',
      h2a: 'Your first 4-language',
      h2b: 'product page is free.',
      sub1: 'Start in 30 seconds · Instant results',
      sub2: '🇰🇷 Korean · 🇺🇸 English · 🇯🇵 Japanese · 🇨🇳 Chinese',
      cta: 'Start Free — Generate in 4 Languages →',
    },
    footer: {
      desc: 'The #1 AI product description generator for cross-border eCommerce. Upload any form or URL — AI creates expert-level content in 4 languages in 5 minutes.',
      links: [['/', 'Home'],['#features', 'Features'],['#reviews', 'Reviews'],['#pricing', 'Pricing'],['/blog', 'Blog'],['/login', 'Sign in'],['/samples', 'Samples'],['/privacy', 'Privacy']],
      copy: '© 2026 PageAI · pagebeer.beer. All rights reserved.',
      privacy: 'Privacy Policy', terms: 'Terms of Service',
      floatingCta: 'Start Free Now →',
    },
  },

  ja: {
    nav: { how: '仕組み', features: '機能', reviews: 'レビュー', pricing: '料金', blog: 'ブログ', signin: 'ログイン', startFree: '無料で開始' },
    hero: {
      badge: '🔥 1,200人以上のグローバルセラー・プロが利用中',
      h1a: '書類・URLをアップロード。', h1b: 'AIが5分以内に完成させます。', h1c: '4言語対応、グローバル最適化。',
      sub1: '商品ページ・事業計画書・提案書・レポート・課題 — PDF·DOCX問わず。',
      sub1b: '',
      sub2: 'Amazon JP · Tmall · 楽天 · Shopify — プラットフォーム別に完璧に最適化。',
      cta1: '無料で始める', cta2: 'デモを見る ▶',
      stats: [['5分', 'プロレベルの完成'], ['4言語', '同時生成'], ['95%', '外注コスト削減'], ['無料', 'スタート']],
    },
    crossborder: {
      title: '越境モード', badge: '新機能',
      desc1: '4言語 + グローバルプラットフォーム最適化',
      desc2: ' — 1回入力、4カ国同時展開、外注ゼロ。',
      cta: '無料で試す →',
    },
    template: {
      badge: '📋 AI書類自動完成',
      h2a: '書類をアップロード。', h2b: 'AIがプロのように記入します。',
      sub: '課題・事業計画書・提案書・報告書・申請書 — PDF·DOCX·XLSXすべて対応',
      types: ['📝 課題・試験', '💼 事業計画書', '📊 業績レポート', '📝 提案書・RFP', '🏛 公的機関申請書', '🔬 研究・論文', '🎓 学術レポート', '📋 IRピッチデック'],
      flow: [
        { step: '01', title: '書類をアップロード', desc: 'PDF·DOCX·XLSX·PPTXを添付またはテキスト貼り付け', icon: '📤' },
        { step: '02', title: 'AI自動分析', desc: '書類の構造を把握し、すべての項目を自動入力', icon: '⚡' },
        { step: '03', title: 'プロレベルの完成', desc: '4言語同時生成対応。PDF·DOCXでダウンロード', icon: '✅' },
      ],
      cta: 'AI書類自動完成を無料で試す →',
      proof: 'ベータユーザーの平均作成時間92%短縮',
      demo: {
        dragDrop: 'ファイルをドラッグまたはクリック',
        fileBtn: 'ファイル選択',
        parsed: '書式解析完了 — 事業計画書.docx',
        fields: [['会社名', 'PageAI Inc.'], ['事業目的', 'AI文書自動化SaaS'], ['ターゲット市場', '日韓中クロスボーダー'], ['想定売上', '1億円（初年度）']],
        multiLang: '4言語同時生成',
        startBtn: '⚡ AI自動補完を開始',
      },
    },
    platformBar: '主要グローバルプラットフォームに完全対応',
    how: {
      label: '仕組み',
      h2a: '商品アイデアから4言語コンテンツまで',
      h2b: '2分以内。',
      steps: [
        { n: '01', icon: '🔗', title: 'URLまたは商品説明を入力', desc: '楽天・Amazon・Tmall・ShopifyなどのURL、または簡単な商品説明を入力するだけ。AIが全項目を自動入力します。', badge: '約30秒' },
        { n: '02', icon: '⚡', title: 'AIが4言語を同時生成', desc: 'ワンクリックで日本語・英語・韓国語・中国語を同時出力。翻訳ではなく、文化的ローカライズ。', badge: '約60秒' },
        { n: '03', icon: '📦', title: 'エクスポート & 即時掲載', desc: 'ZIP一括ダウンロード、コピー&ペースト、PDF出力。Amazon A+、天猫详情页、楽天商品ページ形式に完全対応。', badge: '1クリック' },
      ],
    },
    features: {
      label: '主要機能',
      h2a: 'グローバルセラーに',
      h2b: '本当に必要な機能。',
      card1: { badge: '🌏 フラッグシップ機能', title: '4言語同時生成', desc: '1回の入力で文化的に最適化された4つの出力。日本語は敬語スタイル、中国語は天猫爆款、英語はAmazon A+形式。' },
      card2: { title: 'URL自動入力', desc: '商品URLを貼り付けるだけで、AIが10秒以内に分析し全項目を自動入力。' },
      card3: { title: '転換率予測', desc: '生成後、市場別の予想コンバージョン率（CVR）を自動提供。' },
      card4: { badge: '🛒 プラットフォーム対応', title: 'プラットフォーム自動最適化', desc: 'プラットフォームを選ぶだけでコンテンツを自動フォーマット。Amazon A+（5箇条）、天猫详情页、楽天商品説明に対応。' },
    },
    demo: {
      label: 'ライブデモ',
      h2a: '自動発行フローを',
      h2b: 'リアルタイムで確認。',
      sub: '入力 → AI4言語同時生成 → Amazon・Tmall・楽天・Shopify最適化',
    },
    stats: [
      { v: '4', unit: '言語', sub: '1回の生成で', color: 'from-blue-600 to-violet-600' },
      { v: '6', unit: 'プラットフォーム', sub: '自動最適化', color: 'from-emerald-500 to-teal-500' },
      { v: '2倍', unit: '転換率', sub: '翻訳との比較', color: 'from-orange-500 to-amber-400' },
      { v: '95%', unit: 'コスト削減', sub: '外注との比較', color: 'from-rose-500 to-pink-500' },
    ],
    data: {
      label: '実際のセラー成果 — ベータテスターデータ',
      items: [
        { before: '2週間', after: '5分', label: 'コンテンツ制作時間', delta: '↓97%', color: 'text-blue-600', bg: 'bg-blue-50 border-blue-200' },
        { before: '$2,400', after: '¥4,480', label: '4言語コンテンツ費/月', delta: '↓99%', color: 'text-violet-600', bg: 'bg-violet-50 border-violet-200' },
        { before: '1.2%', after: '2.8%', label: 'Amazon JP コンバージョン率', delta: '+133%', color: 'text-emerald-600', bg: 'bg-emerald-50 border-emerald-200' },
        { before: '1カ国', after: '4カ国', label: '同時ローンチ市場数', delta: '4倍', color: 'text-orange-500', bg: 'bg-orange-50 border-orange-200' },
      ],
    },
    reviews: {
      label: '実際のレビュー',
      h2a: '乗り換えたセラーは',
      h2b: '戻りませんでした。',
      items: [
        { name: 'イ・ジユン', role: 'ビューティー越境セラー (KR→JP)', badge: '翻訳費90%削減', text: '楽天スタイルの敬語がすぐに出てきます。ニュアンスのズレなし。翻訳費を月4万円節約できました。' },
        { name: 'コ・ウビン', role: 'Amazon JPセラー', badge: 'Amazonローンチ5倍速', text: 'Amazon A+コンテンツの箇条書きが自動で完璧に出力されます。コピーライター不要。ローンチ速度が完全に変わりました。' },
        { name: 'シン・ジェヨン', role: 'Tmallグローバルブランド担当', badge: 'Tmall CTR +22%', text: '天猫爆款スタイルがそのまま出てきます。単純翻訳ではなく本物のローカライズ。CTRが1週間で上がりました。' },
        { name: 'チョ・スヤン', role: 'D2Cヘルスケアブランド代表', badge: '4カ国同時ローンチ', text: 'KR・EN・JP・CNが同時に出るのは本当にゲームチェンジャーです。各言語を外注していましたが、今は1人で4カ国同時展開しています。' },
        { name: 'パク・ミンジュン', role: 'Qoo10ビューティーセラー', badge: 'プラットフォーム自動最適化', text: '越境モード → Qoo10選択 → ぴったりの形式で出力。コピペするだけで完了。ワークフローが劇的に楽になりました。' },
        { name: 'キム・ソヒョン', role: 'Shopifyグローバルストア', badge: 'コンバージョン2倍', text: 'EN・JP・CNを同時に文化的ニュアンスまで対応するAIは他にありません。PageAIは本当に別格です。' },
      ],
    },
    faq: {
      label: 'よくある質問',
      h2a: 'ご質問に',
      h2b: 'お答えします。',
      items: [
        { q: '本当に4言語を同時に生成できますか？', a: 'はい。「全言語」を選択すると、韓国語・英語・日本語・中国語を1回の生成で出力します。翻訳ではなく文化的ローカライズ — 日本語は敬語スタイル、中国語は天猫スタイル、英語はAmazon A+形式です。' },
        { q: 'Amazon JP・楽天・Tmallに直接使えますか？', a: 'はい。越境モードでプラットフォームを選択すると、Amazon A+（5箇条）、Tmall详情页構造、楽天商品ページ形式に自動フォーマットされます。手動修正不要です。' },
        { q: '翻訳ではなく本物のローカライズですか？', a: '本物のローカライズです。日本：季節感・敬語・品質の信頼性。中国：KOL言及・社会的証明・プロモーション優先。英語：ベネフィット優先・数値による信頼構造。これらは翻訳とは全く異なります。' },
        { q: 'URLを貼り付けるだけで自動入力されますか？', a: 'はい。楽天・Amazon・Shopifyなど、どのURLでも貼り付けると、AIが10秒以内に分析して商品名・カテゴリ・説明を自動入力します。' },
        { q: '1セット作るのにどのくらい時間がかかりますか？', a: '入力30秒 + 生成60秒 = 合計2分以内。多言語外注の場合、2週間以上待つ作業と比べてください。' },
        { q: '外注費用と比較するとどのくらい節約できますか？', a: '多言語外注費：月10～30万円。PageAI Pro（月4,480円）で無制限生成。95%以上のコスト削減です。' },
      ],
    },
    useCases: {
      label: '利用シーン',
      h2a: '越境セラーから大学院生まで',
      h2b: '5分を取り戻します。',
      items: [
        { title: '越境セラー', role: 'Amazon JP · 天猫 · 楽天', pain: 'プラットフォームごとに外注費が月数十万円', gain: '1回入力 → 4言語プラットフォーム最適化を同時完成。外注費95%削減。' },
        { title: '事業計画書・提案書作成者', role: 'スタートアップ · コンサルタント', pain: '事業計画書の空欄を埋めるのに数日かかる', gain: '書式をアップロード → AIがすべての項目を論理的に自動完成。' },
        { title: '大学生・大学院生', role: '課題・試験・論文', pain: '課題書式の理解と記入に半日かかる', gain: 'PDF課題をアップロード → AIが学術スタイルで全項目を完成。' },
        { title: '企業マーケター', role: '提案書・IRデック', gain: '既存の書式を添付 → AIが説得力ある内容で記入。', pain: 'IRピッチデック・RFP提案書をゼロから作成する負担' },
        { title: 'コンテンツクリエイター', role: 'ネイバーブログ · SNS', pain: 'SEO最適化レビュー記事の執筆に多大な時間', gain: 'URLを入力 → プラットフォームスタイルに合った自然なレビューを自動生成。' },
        { title: 'グローバルブランド担当者', role: '4カ国同時ローンチ', pain: '言語別エージェンシー管理＋翻訳QAで数週間', gain: '1回作成 → 4言語の文化的ローカライズを同日完了。' },
      ],
    },
    comparison: {
      label: 'なぜPageAI？',
      h2a: '外注・ChatGPTと',
      h2b: '直接比較しました。',
      rows: [
        { feature: '4言語同時生成', outsource: false, chatgpt: '△ 手動繰り返し', pageai: true },
        { feature: 'プラットフォーム別自動フォーマット', outsource: true, chatgpt: false, pageai: true },
        { feature: '書類・PDF自動分析＆完成', outsource: '△ 手動ブリーフィング', chatgpt: false, pageai: true },
        { feature: 'URL → 商品情報自動抽出', outsource: false, chatgpt: false, pageai: true },
        { feature: '文化的ローカライズ（翻訳ではない）', outsource: '△ 追加費用', chatgpt: '△ 手動プロンプト', pageai: true },
        { feature: '費用', outsource: '月10〜30万円', chatgpt: '$20/月（手動）', pageai: '無料で開始' },
        { feature: '完成までの時間', outsource: '3〜14日', chatgpt: '1〜3時間', pageai: '5分以内' },
      ],
      cols: { outsource: '外注エージェンシー', chatgpt: 'ChatGPT / Claude', pageai: 'PageAI ✓' },
    },
    finalCta: {
      label: 'グローバル展開の準備はできていますか？',
      h2a: '最初の4言語',
      h2b: '商品ページは無料です。',
      sub1: 'カード不要 · 30秒でスタート',
      sub2: '🇰🇷 韓国語 · 🇺🇸 英語 · 🇯🇵 日本語 · 🇨🇳 中国語',
      cta: '最初のページを無料で作る →',
    },
    footer: {
      desc: 'どんな商品も5分で4言語グローバル販売マシンへ。',
      links: [['/', 'ホーム'],['#features', '機能'],['#reviews', 'レビュー'],['#pricing', '料金'],['/blog', 'ブログ'],['/login', 'ログイン'],['/samples', 'サンプル'],['/privacy', 'プライバシー']],
      copy: '© 2026 PageAI · pagebeer.beer. 全著作権保有。',
      privacy: 'プライバシーポリシー', terms: '利用規約',
      floatingCta: '無料で始める — カード不要',
    },
  },

  zh: {
    nav: { how: '工作原理', features: '核心功能', reviews: '用户评价', pricing: '定价', blog: '博客', signin: '登录', startFree: '免费开始' },
    hero: {
      badge: '🔥 全球1,200+卖家与专业人士信赖使用',
      h1a: '上传表格或链接。', h1b: 'AI在5分钟内完成，', h1c: '支持4种语言。',
      sub1: '商品详情页·商业计划书·提案书·报告·作业 — PDF·DOCX任意格式。',
      sub1b: '',
      sub2: '天猫 · Amazon JP · 楽天 · Shopify — 按平台完美优化。',
      cta1: '立即免费开始', cta2: '观看演示 ▶',
      stats: [['5分钟', '专家级文档'], ['4种语言', '同时生成'], ['95%', '外包成本节省'], ['免费', '即可开始']],
    },
    crossborder: {
      title: '跨境模式', badge: '新功能',
      desc1: '4种语言 + 全球平台优化',
      desc2: ' — 一次输入，四国同时上线，无需外包。',
      cta: '免费试用 →',
    },
    template: {
      badge: '📋 AI表格自动填写',
      h2a: '上传任意表格。', h2b: 'AI像专家一样为您填写。',
      sub: '作业·商业计划书·提案书·报告·申请书 — PDF·DOCX·XLSX全格式支持',
      types: ['📝 作业·考试', '💼 商业计划书', '📊 业绩报告', '📝 提案书·RFP', '🏛 政府申请书', '🔬 研究论文', '🎓 学术报告', '📋 IR路演PPT'],
      flow: [
        { step: '01', title: '上传表格', desc: '附上PDF·DOCX·XLSX·PPTX或粘贴文本', icon: '📤' },
        { step: '02', title: 'AI自动分析', desc: 'AI识别文档结构，自动填写所有字段', icon: '⚡' },
        { step: '03', title: '专家级成果', desc: '支持4语言同时生成，PDF·DOCX下载', icon: '✅' },
      ],
      cta: '免费体验AI表格自动填写 →',
      proof: '测试用户平均节省92%写作时间',
      demo: {
        dragDrop: '拖放文件或点击选择',
        fileBtn: '选择文件',
        parsed: '表格解析完成 — 商业计划书.docx',
        fields: [['公司名称', 'PageAI Inc.'], ['业务目标', 'AI文档自动化SaaS'], ['目标市场', '中日韩跨境电商'], ['预计营收', '1千万元（第1年）']],
        multiLang: '4种语言同时生成',
        startBtn: '⚡ 启动AI自动填写',
      },
    },
    platformBar: '针对所有主要全球平台进行优化',
    how: {
      label: '工作原理',
      h2a: '从产品到4语言内容',
      h2b: '2分钟内完成。',
      steps: [
        { n: '01', icon: '🔗', title: '粘贴链接或描述产品', desc: '粘贴任意商品链接（天猫、Amazon、Shopify等）或简单描述产品。AI自动填写所有字段。', badge: '约30秒' },
        { n: '02', icon: '⚡', title: 'AI同时生成4种语言', desc: '一键 → 中文·英语·日语·韩语同时输出。真正的文化本地化，而非简单翻译。', badge: '约60秒' },
        { n: '03', icon: '📦', title: '导出并立即发布', desc: '下载ZIP压缩包、复制到平台或导出PDF。Amazon A+、天猫详情页、楽天商品页 — 格式完美匹配。', badge: '一键完成' },
      ],
    },
    features: {
      label: '核心功能',
      h2a: '全球卖家',
      h2b: '真正需要的一切。',
      card1: { badge: '🌏 核心特色', title: '4语言同时生成', desc: '一次输入，四个文化适配输出。日语采用敬语风格，中文采用天猫爆款格式，英语采用Amazon A+格式。' },
      card2: { title: 'URL自动填充', desc: '粘贴任意商品链接，AI在10秒内自动分析并填写所有字段。' },
      card3: { title: '转化率预测器', desc: '生成后自动提供各市场预估转化率（CVR）提升数据。' },
      card4: { badge: '🛒 平台智能优化', title: '全平台自动优化', desc: '选择平台 → 内容自动格式化。Amazon A+（5条卖点）、天猫详情页结构、楽天商品页风格。零手动操作。' },
    },
    demo: {
      label: '实时演示',
      h2a: '实时观看',
      h2b: '自动发布全流程。',
      sub: '输入 → AI 4语言同时生成 → Amazon·天猫·楽天·Shopify优化',
    },
    stats: [
      { v: '4', unit: '种语言', sub: '每次生成', color: 'from-blue-600 to-violet-600' },
      { v: '6', unit: '个平台', sub: '自动优化', color: 'from-emerald-500 to-teal-500' },
      { v: '2倍', unit: '转化率', sub: '对比普通翻译', color: 'from-orange-500 to-amber-400' },
      { v: '95%', unit: '成本节省', sub: '对比外包', color: 'from-rose-500 to-pink-500' },
    ],
    data: {
      label: '真实卖家数据 — Beta测试用户',
      items: [
        { before: '2周', after: '5分钟', label: '内容制作时间', delta: '↓97%', color: 'text-blue-600', bg: 'bg-blue-50 border-blue-200' },
        { before: '$2,400', after: '¥210', label: '4语言内容月成本', delta: '↓99%', color: 'text-violet-600', bg: 'bg-violet-50 border-violet-200' },
        { before: '1.2%', after: '2.8%', label: 'Amazon JP转化率', delta: '+133%', color: 'text-emerald-600', bg: 'bg-emerald-50 border-emerald-200' },
        { before: '1个市场', after: '4个市场', label: '同时上线市场', delta: '4倍', color: 'text-orange-500', bg: 'bg-orange-50 border-orange-200' },
      ],
    },
    reviews: {
      label: '真实用户评价',
      h2a: '切换过来的卖家',
      h2b: '都没有回头。',
      items: [
        { name: '李智允', role: '美妆跨境卖家 (KR→JP)', badge: '翻译费节省90%', text: '楽天敬语风格输出秒速到位，没有语气偏差。每月节省翻译费约2000元。' },
        { name: '高宇彬', role: 'Amazon JP卖家', badge: 'Amazon上线速度5倍', text: 'Amazon A+内容五条卖点自动排好格式。不用再请文案，上线速度彻底变了。' },
        { name: '申在妍', role: 'Tmall全球品牌负责人', badge: 'Tmall点击率+22%', text: '天猫爆款风格直接输出。不是翻译，是真正的本地化。点击率一周内就上升了。' },
        { name: '曹秀洋', role: 'D2C健康品牌创始人', badge: '4国同时上线', text: 'KR·EN·JP·CN同时出来真是游戏规则改变者。以前每种语言单独外包，现在我一个人做4国同时上线。' },
        { name: '朴敏俊', role: 'Qoo10美妆卖家', badge: '平台自动优化', text: '跨境模式 → 选Qoo10 → 输出完美格式。复制粘贴即完成。工作流程变得无比顺畅。' },
        { name: '金瑞贤', role: 'Shopify全球店铺', badge: '转化率提升2倍', text: '能同时处理EN/JP/CN文化差异的AI真的只有PageAI。完全不一样的级别。' },
      ],
    },
    faq: {
      label: '常见问题',
      h2a: '有问题？',
      h2b: '我们来解答。',
      items: [
        { q: '真的可以同时生成4种语言吗？', a: '是的。选择"全部语言"，一次生成即可输出中文·英语·日语·韩语 — 每种语言都经过文化本地化。日语采用敬语风格，中文采用天猫社交证明结构，英语采用Amazon A+格式。' },
        { q: '支持直接用于Amazon JP、天猫和楽天吗？', a: '支持。在跨境模式中选择平台，内容自动格式化：Amazon A+（5条卖点）、天猫详情页结构、楽天商品页风格。无需手动调整。' },
        { q: '是真正的本地化还是机器翻译？', a: '真正的本地化。日本：季节感·敬意·品质信赖。中国：KOL背书·社交证明·促销优先。英语：利益优先·数据驱动信任。各国家有其独特的说服逻辑，与翻译完全不同。' },
        { q: '粘贴链接就能自动填充吗？', a: '是的。粘贴任意商品链接（天猫、京东、Amazon、Shopify等），AI在约10秒内分析页面并自动填写产品名称、品类和描述。' },
        { q: '制作一套内容需要多长时间？', a: '输入30秒 + 生成60秒 = 总计2分钟以内。与多语言外包需要等待2周以上相比，效率天壤之别。' },
        { q: '与外包相比能节省多少费用？', a: '多语言外包费用：每月5,000~20,000元以上。PageAI专业版（¥210/月）可无限次生成。节省95%以上的费用。' },
      ],
    },
    useCases: {
      label: '适用场景',
      h2a: '从跨境卖家到研究生',
      h2b: '都能找回那5分钟。',
      items: [
        { title: '跨境卖家', role: 'Amazon JP · 天猫 · 楽天', pain: '每个平台分别外包，每月花费数千元', gain: '一次输入 → 4语言平台优化同时完成。外包费用减少95%。' },
        { title: '商业计划书·提案书撰写者', role: '创业者 · 顾问', pain: '填写商业计划书模板需要好几天', gain: '上传模板 → AI自动以逻辑性强的内容填写所有项目。' },
        { title: '学生', role: '作业·考试·论文', pain: '理解并填写作业表格耗费半天时间', gain: '上传PDF作业 → AI以学术风格完成所有栏目。' },
        { title: '企业营销人员', role: '提案书 · IR路演', pain: '从零开始撰写IR路演PPT和RFP提案书压力大', gain: '附上现有模板 → AI填充有说服力的结构化内容。' },
        { title: '内容创作者', role: 'Naver博客 · 社交媒体', pain: 'SEO优化评测文章写作耗时过多', gain: '粘贴链接 → AI自动生成符合平台风格的自然评测内容。' },
        { title: '全球品牌负责人', role: '4国同时上线', pain: '管理各语言机构+翻译QA耗费数周', gain: '一次撰写 → 4语言文化本地化当天完成。' },
      ],
    },
    comparison: {
      label: '为什么选PageAI',
      h2a: '与外包和ChatGPT',
      h2b: '直接对比。',
      rows: [
        { feature: '4语言同时生成', outsource: false, chatgpt: '△ 手动重复', pageai: true },
        { feature: '平台专属自动格式（Amazon A+，天猫等）', outsource: true, chatgpt: false, pageai: true },
        { feature: '表格/PDF自动分析与填写', outsource: '△ 手动说明', chatgpt: false, pageai: true },
        { feature: '链接 → 自动提取产品信息', outsource: false, chatgpt: false, pageai: true },
        { feature: '文化本地化（非翻译）', outsource: '△ 额外收费', chatgpt: '△ 手动提示', pageai: true },
        { feature: '费用', outsource: '$800–$2,400/月', chatgpt: '$20/月（手动）', pageai: '免费开始' },
        { feature: '完成时间', outsource: '3–14天', chatgpt: '1–3小时', pageai: '5分钟以内' },
      ],
      cols: { outsource: '外包机构', chatgpt: 'ChatGPT / Claude', pageai: 'PageAI ✓' },
    },
    finalCta: {
      label: '准备好进军全球了吗？',
      h2a: '您的第一个4语言',
      h2b: '商品页面完全免费。',
      sub1: '无需信用卡 · 30秒即可开始',
      sub2: '🇰🇷 韩语 · 🇺🇸 英语 · 🇯🇵 日语 · 🇨🇳 中文',
      cta: '免费创建我的第一个页面 →',
    },
    footer: {
      desc: '让任何产品在5分钟内成为4语言全球销售利器。',
      links: [['/', '首页'],['#features', '功能'],['#reviews', '评价'],['#pricing', '定价'],['/blog', '博客'],['/login', '登录'],['/samples', '样本'],['/privacy', '隐私政策']],
      copy: '© 2026 PageAI · pagebeer.beer. 版权所有。',
      privacy: '隐私政策', terms: '服务条款',
      floatingCta: '立即免费开始 — 无需信用卡',
    },
  },
}
